package org.school.manager.model;

import java.util.Date;

public class Students {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sId
     *
     * @mbggenerated
     */
    private String sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sName
     *
     * @mbggenerated
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.nSex
     *
     * @mbggenerated
     */
    private Integer nsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sIdCard
     *
     * @mbggenerated
     */
    private String sidcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.nSchoolNo
     *
     * @mbggenerated
     */
    private Integer nschoolno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sStudentNo
     *
     * @mbggenerated
     */
    private String sstudentno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sClass
     *
     * @mbggenerated
     */
    private String sclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sPhone
     *
     * @mbggenerated
     */
    private String sphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sEmail
     *
     * @mbggenerated
     */
    private String semail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sWeiXin
     *
     * @mbggenerated
     */
    private String sweixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sQQ
     *
     * @mbggenerated
     */
    private String sqq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sMark
     *
     * @mbggenerated
     */
    private String smark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.dCreate
     *
     * @mbggenerated
     */
    private Date dcreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sId
     *
     * @return the value of students.sId
     *
     * @mbggenerated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sId
     *
     * @param sid the value for students.sId
     *
     * @mbggenerated
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sName
     *
     * @return the value of students.sName
     *
     * @mbggenerated
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sName
     *
     * @param sname the value for students.sName
     *
     * @mbggenerated
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.nSex
     *
     * @return the value of students.nSex
     *
     * @mbggenerated
     */
    public Integer getNsex() {
        return nsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.nSex
     *
     * @param nsex the value for students.nSex
     *
     * @mbggenerated
     */
    public void setNsex(Integer nsex) {
        this.nsex = nsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sIdCard
     *
     * @return the value of students.sIdCard
     *
     * @mbggenerated
     */
    public String getSidcard() {
        return sidcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sIdCard
     *
     * @param sidcard the value for students.sIdCard
     *
     * @mbggenerated
     */
    public void setSidcard(String sidcard) {
        this.sidcard = sidcard == null ? null : sidcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.nSchoolNo
     *
     * @return the value of students.nSchoolNo
     *
     * @mbggenerated
     */
    public Integer getNschoolno() {
        return nschoolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.nSchoolNo
     *
     * @param nschoolno the value for students.nSchoolNo
     *
     * @mbggenerated
     */
    public void setNschoolno(Integer nschoolno) {
        this.nschoolno = nschoolno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sStudentNo
     *
     * @return the value of students.sStudentNo
     *
     * @mbggenerated
     */
    public String getSstudentno() {
        return sstudentno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sStudentNo
     *
     * @param sstudentno the value for students.sStudentNo
     *
     * @mbggenerated
     */
    public void setSstudentno(String sstudentno) {
        this.sstudentno = sstudentno == null ? null : sstudentno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sClass
     *
     * @return the value of students.sClass
     *
     * @mbggenerated
     */
    public String getSclass() {
        return sclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sClass
     *
     * @param sclass the value for students.sClass
     *
     * @mbggenerated
     */
    public void setSclass(String sclass) {
        this.sclass = sclass == null ? null : sclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sPhone
     *
     * @return the value of students.sPhone
     *
     * @mbggenerated
     */
    public String getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sPhone
     *
     * @param sphone the value for students.sPhone
     *
     * @mbggenerated
     */
    public void setSphone(String sphone) {
        this.sphone = sphone == null ? null : sphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sEmail
     *
     * @return the value of students.sEmail
     *
     * @mbggenerated
     */
    public String getSemail() {
        return semail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sEmail
     *
     * @param semail the value for students.sEmail
     *
     * @mbggenerated
     */
    public void setSemail(String semail) {
        this.semail = semail == null ? null : semail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sWeiXin
     *
     * @return the value of students.sWeiXin
     *
     * @mbggenerated
     */
    public String getSweixin() {
        return sweixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sWeiXin
     *
     * @param sweixin the value for students.sWeiXin
     *
     * @mbggenerated
     */
    public void setSweixin(String sweixin) {
        this.sweixin = sweixin == null ? null : sweixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sQQ
     *
     * @return the value of students.sQQ
     *
     * @mbggenerated
     */
    public String getSqq() {
        return sqq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sQQ
     *
     * @param sqq the value for students.sQQ
     *
     * @mbggenerated
     */
    public void setSqq(String sqq) {
        this.sqq = sqq == null ? null : sqq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sMark
     *
     * @return the value of students.sMark
     *
     * @mbggenerated
     */
    public String getSmark() {
        return smark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sMark
     *
     * @param smark the value for students.sMark
     *
     * @mbggenerated
     */
    public void setSmark(String smark) {
        this.smark = smark == null ? null : smark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.dCreate
     *
     * @return the value of students.dCreate
     *
     * @mbggenerated
     */
    public Date getDcreate() {
        return dcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.dCreate
     *
     * @param dcreate the value for students.dCreate
     *
     * @mbggenerated
     */
    public void setDcreate(Date dcreate) {
        this.dcreate = dcreate;
    }
}