package org.school.manager.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.school.manager.model.Students;
import org.school.manager.model.StudentsExample;

public interface StudentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int countByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int deleteByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int insert(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int insertSelective(Students record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    List<Students> selectByExample(StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Students record, @Param("example") StudentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Students record, @Param("example") StudentsExample example);
}